### ISSUE TITLE
[Feature Request] Support Koboldcpp Dynamic Temperature 

### ISSUE THREAD

**Issue by IdiotSandwichTheThird** [lmg-anon/mikupad#15]
It was recently added in [1.55.1](https://github.com/LostRuins/koboldcpp/releases/tag/v1.55.1) and I think it's a really cool feature :)

https://github.com/LostRuins/koboldcpp/pull/600

**Comment by lmg-anon** [comment]
Should be supported as of https://github.com/lmg-anon/mikupad/commit/3940b968d98c0f35afd3e5594e7db03e528ac56e
