### ISSUE TITLE
Preserving cursor position during generation

### ISSUE THREAD

**Issue by culturedniichan** [lmg-anon/mikupad#17]
One issue I have, but that seems to be on purpose, is that the cursor, after running the prediction, does not go to the end of the new generated text.

Personally I'd find it useful because if I like what the AI generated, I may wish to continue writing from there. Additionally, with very long generations, the text area will scroll down to the end, but the cursor will be up and out of view, which seems a bit unintuitive to me.

The code doing this has the following comment:

```
// Update the textarea in an uncontrolled way so the user doesn't lose their
// selection or cursor position during prediction
```

Since it is mentioned that it also preserves "selection", I assume there is a genuine case for wanting to preserve a selection. However, with no selected text, I find this hard to work with if I want to co-write with the AI.

For personal use I will modify it to move the cursor to the end unless there is a selection, but don't know if a PR for this would be in order.

**Comment by neCo2** [comment]
I'd could use that too. You could probably just add it as a setting in the "Editor Preferences" modal.

**Comment by lmg-anon** [comment]
I agree with @neCo2, PRs adding checkboxes to the "Editor Preferences" modal are very welcome.

**Comment by culturedniichan** [comment]
PR done
