### ISSUE TITLE
[Feature Request] Listen over network

### ISSUE THREAD

**Issue by official-elinas** [lmg-anon/mikupad#34]
It would be nice to incorporate a way to have this being accessible over your LAN, such as a flag like `--listen "local_IP"` 

This would make it accessible on mobile devices as well as other devises where the database is not stored, ie. being hosted a server.

I really like the simplicity and simple writing pad of the software, and an addition like this would enhance it greatly.

**Comment by lmg-anon** [comment]
I started implementing this, you can try it using this branch: https://github.com/lmg-anon/mikupad/tree/server

**Comment by reversebias** [comment]
Since it's a single html, it's been working great for me to just run:
`python3 -m http.server` inside the mikupad directory. Browse to http://hostname.local:8000/mikupad.html

**Comment by lmg-anon** [comment]
> Since it's a single html, it's been working great for me to just run: `python3 -m http.server` inside the mikupad directory. Browse to http://hostname.local:8000/mikupad.html

You don't need to run an HTTP server. Simply opening the HTML from any browser, even from your phone, is sufficient.

**Comment by lmg-anon** [comment]
You can now make Mikupad accessible over the LAN using the server. You just need to install Node.js and run `start.bat` (for Windows) or `start.sh` (for Linux/Mac) inside the server folder.
