### ISSUE TITLE
[Bug] Pressing Ctrl+R during generation borks state

### ISSUE THREAD

**Issue by m18coppola** [lmg-anon/mikupad#37]
While text is being streamed during prediction, you can still press Ctrl+R to regenerate. This causes the text window to print tokens being streamed from two different requests and inadvertently interleaves the output resulting in jumbled text.

**Comment by lmg-anon** [comment]
Thank you for the bug report! Fixed in dc4b2c59dba7e29713e78251c8358b04c7b2bd0a.
