### ISSUE TITLE
[Bug] Unable to access externally hosted APIs

### ISSUE THREAD

**Issue by cosmojg** [lmg-anon/mikupad#38]
I get the following errors when attempting to access APIs on other servers (regardless of whether it's KoboldCpp, OpenRouter, or OpenAI proper). This happens both using the hosted demo and when running from the HTML file locally:

## Firefox

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://openrouter.ai/v1/internal/token-count. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://openrouter.ai/v1/internal/token-count. (Reason: CORS request did not succeed). Status code: (null).

Uncaught TypeError: NetworkError when attempting to fetch resource.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://openrouter.ai/v1/models. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://openrouter.ai/v1/models. (Reason: CORS request did not succeed). Status code: (null).

Uncaught TypeError: NetworkError when attempting to fetch resource.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://openrouter.ai/v1/token/encode. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://openrouter.ai/v1/token/encode. (Reason: CORS request did not succeed). Status code: (null).

Uncaught TypeError: NetworkError when attempting to fetch resource.

## Chrome

Access to fetch at 'https://openrouter.ai/v1/completions' from origin 'https://lmg-anon.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
openrouter.ai/v1/completions:1 
        
        
       Failed to load resource: net::ERR_FAILED
mikupad.html:1165 
        
        
       
        
       Uncaught TypeError: Failed to fetch
    at openaiCompletion (mikupad.html:1165:20)
    at openaiCompletion.next (<anonymous>)
    at completion (mikupad.html:911:18)
    at async predict (mikupad.html:2194:21)
mikupad.html:1 Access to fetch at 'https://openrouter.ai/v1/internal/token-count' from origin 'https://lmg-anon.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
openrouter.ai/v1/internal/token-count:1 
        
        
       Failed to load resource: net::ERR_FAILED
mikupad.html:1072 
        
        
       
        
       Uncaught TypeError: Failed to fetch
    at openaiOobaTokenCount (mikupad.html:1072:21)
    at getTokenCount (mikupad.html:885:23)
    at mikupad.html:2417:30
mikupad.html:1 Access to fetch at 'https://openrouter.ai/v1/token/encode' from origin 'https://lmg-anon.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
openrouter.ai/v1/token/encode:1 
        
        
       Failed to load resource: net::ERR_FAILED
mikupad.html:1094 
        
        
       
        
       Uncaught TypeError: Failed to fetch
    at openaiTabbyTokenCount (mikupad.html:1094:21)
    at getTokenCount (mikupad.html:888:23)
    at async mikupad.html:2417:24

**Comment by cosmojg** [comment]
Notably, I still get these issues when running locally with:

`npx serve --cors`

and

`http-server --cors`

**Comment by BugReporterZ** [comment]
I get this error with an `https` server, but not with `http`.

**Comment by lmg-anon** [comment]
Mikupad can only access APIs that have the necessary CORS headers. This is a limitation imposed by web browsers and cannot be circumvented. However, it may be possible to allow requests to be made through an intermediate server, such as a CORS proxy.

**Comment by ewof** [comment]
using https://www.npmjs.com/package/local-cors-proxy
```sh
lcp --proxyUrl https://whatever-random-cloudflare-thingy.trycloudflare.com --port 7878 --credentials --proxyPartial ""
```
and setting my "Server" to `http://localhost:7878/` works for me

**Comment by lmg-anon** [comment]
Now you can use the server located in the server folder to run a server for Mikupad. This server will serve the Mikupad HTML and will also route all requests through the server (when you access Mikupad via the server URL), so CORS shouldn't be an issue in anymore.

**Comment by ewof** [comment]
sorry for necro and this is probably the wrong issue but, would be nice if the server start script had executable perms by default

**Comment by lmg-anon** [comment]
@ewof I don't think this is possible, unless I misunderstood what you mean.

**Comment by tjohnman** [comment]
In the case of OpenRouter, the CORS error only happens because the request URL is wrong and ends up reaching the web server instead of the API proper, which does indeed implement the proper CORS headers. This happens when the API URL is normalized. I proposed a way of fixing it in  #59.
