### ISSUE TITLE
Improve mobile support (feature)

### ISSUE THREAD

**Issue by stepelu** [lmg-anon/mikupad#42]
It would be great to have improved support when accessing from a mobile, i.e. a simple responsive design.
I have the following suggestions:
- collapsible top menu instead of fixed sidebar
- larger font size
- disabling text overlay, I noticed a significant computational effort (but possibly that could also be the fast streaming)

**Comment by lmg-anon** [comment]
>disabling text overlay, I noticed a significant computational effort (but possibly that could also be the fast streaming)

In case you aren't aware, you can disable the text overlay manually in Editor Preferences.
![image](https://github.com/lmg-anon/mikupad/assets/139719567/8c0d0cd3-79fa-45c1-af99-f049b41d5a28)
