### ISSUE TITLE
[Unexpected behaviour] Text shifting when hovering over the handle of the resizeable text area

### ISSUE THREAD

**Issue by neCo2** [lmg-anon/mikupad#52]
Like the title says. Sometimes when the text's in a bad position, and you hover over the edges of the text area, it shifts things by a line. I've attached a video to show what I'm talking about.
[output.webm](https://github.com/lmg-anon/mikupad/assets/50079394/e0eac3e0-7b87-409a-bac7-83dd5cf2803b)
Using Firefox 125.0.2

**Comment by lmg-anon** [comment]
That's because of the borders that were added (not very perceptible because of your theme), I'll just remove them for now since the cursor is already a good feedback that the border can be resized.
https://github.com/lmg-anon/mikupad/commit/ba92241c3d246309f72ef856a8107d2490419364

**Comment by lmg-anon** [comment]
Hm... This broke the ability to resize using the right edge when there's a scroll bar... Looks like I will have to be creative
