### ISSUE TITLE
[Request] Add token IDs to the object yielded by parseEventStream()

### ISSUE THREAD

**Issue by neCo2** [lmg-anon/mikupad#53]
Started working on phrase biasing, and being able to monitor the stream of token ids instead of the token strings would make life much easier for me. I'd do it myself, but I couldn't figure it out.

**Comment by lmg-anon** [comment]
`parseEventStream`'s only job is to return the event stream as json, and it doesn't look like any backend sends back token ids in the completion stream. So I feel like the only choice would be to detokenize each token.

**Comment by neCo2** [comment]
I see, that's a shame. Guess I'll have to figure something out for kobold then.
