### ISSUE TITLE
[Feature Request] Cache Imports

### ISSUE THREAD

**Issue by neCo2** [lmg-anon/mikupad#7]
Currently, mikupad will only cache its imports in the browser cache, so if that is cleared, and you do not have an internet connection, it won't load.
I'm not entirely sure if it's possible, but it'd be great if it could save a version of the dependencies locally, like it does with the sessions and settings, to fall back on when not connected to the internet later.

**Comment by lmg-anon** [comment]
Currently, you can bake the dependencies inside the html using the `compile.bat/.sh` script, the downside is that the file will get unreadable.

**Comment by neCo2** [comment]
Got it, thanks!
