### ISSUE TITLE
The token probability popup still shows all the remaining tokens with "0.00" probability.

### ISSUE THREAD

**Issue by jukofyork** [lmg-anon/mikupad#84]
I just noticed if you set say `minp=0.15` and turn off all the other samplers, that the token probability popup still shows all the remaining tokens with "0.00" probability. It would be nice if these could be hidden so as to get an idea at a glance what tokens have non-zero probability.

**Comment by lmg-anon** [comment]
Yes, that makes sense. Thank you for your contribution.
