### ISSUE TITLE
Token Probabilities Visibility Tied to ‘Highlight Generate Tokens'

### ISSUE THREAD

**Issue by engadine1997** [lmg-anon/mikupad#89]
Not sure if this is intentional behaviour, but recent updates seem to have made the token probability display mutually exclusive with the highlight generate tokens option.

In older versions I could have the highlight disabled and still see tokens probabilities, but this is no longer the case; when you enable the highlight, the submenu for probabilities visibility disappears.

**How it used to work in older versions:**
![old](https://github.com/user-attachments/assets/d7622d1a-046c-4f7f-9392-605eeaf7328e)

**How it works in most recent version:**
![new](https://github.com/user-attachments/assets/27685704-ce24-4d81-850c-dfc7bd014249)

Not a big deal, but it would be nice to see token probabilities without forcing you to turn highlighting on.

**Comment by lmg-anon** [comment]
It is, in fact, on purpose. If the highlight overlay affects performance, disabling the highlight wouldn't have been enough before. I guess the solution would be to add an option to show the highlight only on hover, like it worked before when the highlight for generated tokens was disabled.

**Comment by lmg-anon** [comment]
Implemented on https://github.com/lmg-anon/mikupad/commit/0f96ecb6b3d60c516da2375c85e57f133d9a6f90.
![image](https://github.com/user-attachments/assets/d7bcf5b6-ddfc-4c24-a4bc-438fae15db34)
