### ISSUE TITLE
Logit Bias for exllamav2/tabbyapi

### ISSUE THREAD

**Issue by JPFlare** [lmg-anon/mikupad#92]
Is there any chance for Logit Bias to be implemented for a backend that runs exl2 models?

I would love to use Mikupad, but my preferred format is exl2, and there's no Logit Bias option for these backends that I can find.

**Comment by lmg-anon** [comment]
It's now implemented as of commit https://github.com/lmg-anon/mikupad/commit/f63594a9d65d3f57ce8d948e697496ce0eac1981!

**Comment by JPFlare** [comment]
Thank you very much, and I really appreciate the quick implementation!
