### ISSUE TITLE
Right click context menu (Or a keyboard shortcut of some kind?) for adding Instruct templates and/or {predict} at cursor location

### ISSUE THREAD

**Issue by JPFlare** [lmg-anon/mikupad#96]
Figured I would pitch an idea for shortening the amount of time required to add Instruct templates and {predict} tags for adding something to the middle of a document, and for guiding generation, assuming something like this doesn't already exist, and I just don't know about it.

A lot of the time I'll be reading, and decide "I could use more detail here", or "This could use some more dialogue", and I'll have to either use something like autohotkey, or a mouse macro to add the required tags, or I'll have to click the "Add instruct template" button, then type out {predict} manually. Similarly, I often want to guide the next generation and have to find and click the "Add instruct template" button fairly regularly.

Since I find myself doing this frequently, I figured other people may have the same issue. A right click context menu could be an easy way to give better access to a lot of those types of functions. Keyboard shortcuts may also work if those are possible, similar to how CTRL + ENTER is a shortcut for Predict, but it might not be as quick and accessible as just right clicking at the location you want it.

My ideal implementation would be essentially a macro that adds the instruct template, followed by the {predict} tag, then moves the text cursor to the middle of the instruct template. In my head, the original concept for this was right clicking, choosing "Predict Here", which prompts the user with a dialogue box that says "Type what you want to generate", then you type in what you want the LLM to add, and it automatically adds [INST]what you want to generate[/INST]{predict} and begins prediction, but actual implementation is down to what most people would find most usable IMO.

As an example, I could right click, choose something like "Predict Here", and since I'm using Mistral Large Instruct 2407, it would insert [INST]x[/INST]{predict}, and move the text cursor to where the x is, saving tons of time every time I need it.

I'm not sure if it's feasible to add a right click context menu, as I think that means you would have to either accept the loss of right clicking to undo/copy/paste/select all, or implement that functionality natively, but having an easy way to do the above in any way would improve my productivity a ton, and seems like a great QoL feature that might be useful for other people. I saw that there was an attempt to add the ability to just add an entry to the right click context menu, and it's implemented in Firefox, but I think it was behind a Chrome flag before it was dropped, according to the Google results I found.

Thanks for your time, and let me know if there's another avenue to suggest features that you would prefer, rather than creating Issues for each one, as I've already submitted three so far, and I don't want to flood you guys with suggestions.

**Comment by lmg-anon** [comment]
Thanks for your suggestion! I’ve implemented the right-click context menu, which opens when you right-click while holding CTRL. Keyboard shortcuts are also a great idea, but I’ll leave them for later.

![image](https://github.com/user-attachments/assets/2386668b-ad7b-40eb-9b32-5ddff1b53c1c)

Here’s a brief description of what each button does:

- **Instruct Here**: Opens a modal where you can prompt the LLM about your story without directly writing in the story itself. It can also be used to ask the LLM something unrelated to the story context.  
- **Predict Here**: Inserts "{predict}" and starts the prediction.  
- **Fill-In-The-Middle Here**: Inserts "{fill}" and starts the prediction.  
- **Insert System/Instruct Template**: Works like the buttons you’re familiar with, but I’ve made a small change, it now automatically inserts "{predict}" if you aren’t at the end of the text area, so it should fit your needs.

Here's an example of how to use the "Instruct Instruct Template":

https://github.com/user-attachments/assets/a03fea58-e6c4-4b7e-8ba6-36e62538fd99
